/**
 * ログ1行から中身を取り出す小道具のテスト。
 *
 * state.mjs と digest.mjs の両方がここに乗っているので、
 * ここが崩れると一覧と詳細の両方が同時に狂う。
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import {
  contentBlocks,
  textOf,
  toolUses,
  toolResults,
  isToolResultEntry,
  isUserPrompt,
  isInterrupt,
  slashCommandOf,
  timestampOf,
  isMainline,
  isSidechain,
  uuidOf,
  agentIdOf,
  taskNotificationOf,
  recapOf,
  DENIAL_KINDS,
  ASK_TOOLS,
} from '../src/parse/entries.mjs';
import { at, say, call, result, prompt } from './helpers.mjs';

test('content が文字列の形も配列に揃える', () => {
  assert.deepEqual(
    contentBlocks({ message: { content: 'そのまま文字列' } }),
    [{ type: 'text', text: 'そのまま文字列' }],
  );
});

test('content が無い行は空配列', () => {
  assert.deepEqual(contentBlocks(null), []);
  assert.deepEqual(contentBlocks({}), []);
  assert.deepEqual(contentBlocks({ message: {} }), []);
  assert.deepEqual(contentBlocks({ message: { content: 42 } }), []);
});

test('textOf は text だけつなぐ。thinking は含めない', () => {
  const entry = {
    type: 'assistant',
    message: {
      content: [
        { type: 'thinking', thinking: '内心の声' },
        { type: 'text', text: '前半' },
        { type: 'tool_use', id: 'x', name: 'Bash', input: {} },
        { type: 'text', text: '後半' },
      ],
    },
  };
  assert.equal(textOf(entry), '前半\n後半');
});

test('textOf は前後の空白を落とす', () => {
  assert.equal(textOf({ message: { content: '  \n はい \n ' } }), 'はい');
});

test('toolUses は input が無くても空オブジェクトを返す', () => {
  const entry = {
    type: 'assistant',
    message: { content: [{ type: 'tool_use', id: 't1', name: 'Read' }] },
  };
  assert.deepEqual(toolUses(entry), [{ id: 't1', name: 'Read', input: {} }]);
});

test('toolResults は content が文字列でも配列でも本文を取り出す', () => {
  const entry = {
    type: 'user',
    message: {
      content: [
        { type: 'tool_result', tool_use_id: 'a', content: 'ただの文字列' },
        {
          type: 'tool_result',
          tool_use_id: 'b',
          is_error: true,
          content: [{ type: 'text', text: '1行目' }, { type: 'image' }, { type: 'text', text: '2行目' }],
        },
        { type: 'tool_result', tool_use_id: 'c', content: { unexpected: true } },
      ],
    },
  };
  assert.deepEqual(toolResults(entry), [
    { id: 'a', isError: false, text: 'ただの文字列' },
    { id: 'b', isError: true, text: '1行目\n2行目' },
    // 知らない形が来ても落とさず、本文だけ空にして進める
    { id: 'c', isError: false, text: '' },
  ]);
});

test('isToolResultEntry は tool_result ブロックと toolUseResult の両方を見る', () => {
  assert.equal(isToolResultEntry(result('t1')), true);
  assert.equal(
    isToolResultEntry({
      type: 'user',
      message: { content: [{ type: 'tool_result', tool_use_id: 't1', content: 'ok' }] },
    }),
    true,
  );
  assert.equal(isToolResultEntry({ type: 'user', toolUseResult: { stdout: '' } }), true);
  assert.equal(isToolResultEntry(prompt('ふつうの指示')), false);
  assert.equal(isToolResultEntry(say('assistant の発言')), false);
});

test('isUserPrompt は自分が打った指示だけを通す', () => {
  assert.equal(isUserPrompt(prompt('これやって')), true);
});

test('isUserPrompt が外すもの', () => {
  const cases = [
    ['assistant の行', say('発言')],
    ['ツール結果', result('t1')],
    ['isMeta が立った行', { ...prompt('メタ情報'), isMeta: true }],
    ['本文が空', prompt('   ')],
    ['スラッシュコマンドの展開', prompt('<command-name>/pr-review</command-name>')],
    ['コマンドのメッセージ', prompt('<command-message>pr-review is running</command-message>')],
    ['コマンドの引数', prompt('<command-args>1234</command-args>')],
    ['ローカルコマンドの標準出力', prompt('<local-command-stdout>結果</local-command-stdout>')],
    ['ローカルコマンドの標準エラー', prompt('<local-command-stderr>失敗</local-command-stderr>')],
    ['システムが差し込むリマインダ', prompt('<system-reminder>覚えておいて</system-reminder>')],
    ['投入前フック', prompt('<user-prompt-submit-hook>hook</user-prompt-submit-hook>')],
    ['再開時の注意書き', prompt('Caveat: The messages below were generated by the user while running local commands.')],
    ['圧縮後の引き継ぎ要約', prompt('This session is being continued from a previous conversation. The summary...')],
    ['中断の印', prompt('[Request interrupted by user for tool use]')],
    // サブエージェントの終わりを伝える差し込み。実測84件がここに当たる。
    // 外さないと時系列に XML がそのまま「あなたの指示」として並ぶ
    ['サブエージェントの完了通知', prompt('<task-notification>\n<task-id>a1</task-id>\n</task-notification>')],
  ];
  for (const [label, entry] of cases) {
    assert.equal(isUserPrompt(entry), false, `${label} を指示として拾ってしまっている`);
  }
});

test('isInterrupt は中断の印だけを見つける', () => {
  assert.equal(isInterrupt(prompt('[Request interrupted by user]')), true);
  assert.equal(isInterrupt(prompt('ふつうの指示')), false);
  // assistant 側に同じ文があっても中断ではない
  assert.equal(isInterrupt(say('[Request interrupted by user]')), false);
});

test('slashCommandOf はコマンド名と引数を取り出す', () => {
  assert.deepEqual(
    slashCommandOf(prompt('<command-name>/pr-review</command-name>\n<command-args>1234</command-args>')),
    { command: '/pr-review', args: '1234' },
  );
  assert.deepEqual(
    slashCommandOf(prompt('<command-name>/clear</command-name>')),
    { command: '/clear', args: '' },
  );
  assert.equal(slashCommandOf(prompt('ふつうの指示')), null);
  assert.equal(slashCommandOf(say('<command-name>/x</command-name>')), null);
});

test('timestampOf は数値と ISO 文字列の両方を受ける', () => {
  assert.equal(timestampOf({ timestamp: 1700000000000 }), 1700000000000);
  assert.equal(timestampOf({ timestamp: at(0) }), Date.parse(at(0)));
  assert.equal(timestampOf({ timestamp: '日付じゃない' }), null);
  assert.equal(timestampOf({}), null);
  assert.equal(timestampOf(null), null);
});

test('isMainline はサブエージェントの行だけ外す', () => {
  assert.equal(isMainline(say('本流')), true);
  assert.equal(isMainline({ ...say('枝'), isSidechain: true }), false);
  assert.equal(isMainline({ ...say('枝'), isSidechain: false }), true);
  assert.equal(isMainline(null), true);
});

test('isSidechain は isMainline の真裏', () => {
  const branch = { ...say('枝'), isSidechain: true };
  assert.equal(isSidechain(branch), true);
  assert.equal(isSidechain(say('本流')), false);
  // キーが無い行は本流。サブエージェントの行だけが印を持つ
  assert.equal(isSidechain({}), false);
  assert.equal(isSidechain(null), false);
});

test('uuidOf は文字列のときだけ返す', () => {
  assert.equal(uuidOf({ uuid: 'abc' }), 'abc');
  // 数値や欠落を空文字にすると「取れなかった」と「空だった」が混ざる
  assert.equal(uuidOf({ uuid: 42 }), null);
  assert.equal(uuidOf({}), null);
  assert.equal(uuidOf(null), null);
});

test('recapOf は Claude の中間報告を取り出し、断り書きだけ落とす', () => {
  const withTail = {
    type: 'system',
    subtype: 'away_summary',
    content: '一覧の描画を直しています (disable recaps in /config)',
  };
  assert.equal(recapOf(withTail), '一覧の描画を直しています');

  // 断り書きが付いていない行もある（実測183件中25件）。除去は付いているときだけ
  const bare = { type: 'system', subtype: 'away_summary', content: 'テストを通しました' };
  assert.equal(recapOf(bare), 'テストを通しました');
});

test('recapOf は中間報告以外の行を拾わない', () => {
  // 本文は message.content ではなく entry.content に入る。ここを取り違えると全件が空になる
  assert.equal(recapOf({ type: 'system', subtype: 'away_summary', message: { content: '別の場所' } }), null);
  assert.equal(recapOf({ type: 'system', subtype: 'turn_duration', content: 'ちがう種類' }), null);
  assert.equal(recapOf(say('assistant の発言')), null);
  // 断り書きだけの行は中身が無いので null
  assert.equal(recapOf({ type: 'system', subtype: 'away_summary', content: '(disable recaps in /config)' }), null);
  assert.equal(recapOf({ type: 'system', subtype: 'away_summary', content: 42 }), null);
});

test('agentIdOf はサブエージェントの行だけ値を返す', () => {
  // サブエージェントのログは全行が持っている（実測59行すべて）。親ログの行には無い
  assert.equal(agentIdOf({ ...say('枝の発言'), agentId: 'a1b5fffa' }), 'a1b5fffa');
  assert.equal(agentIdOf(say('本流の発言')), null);
  // 数値を文字列に丸めない。取れなかったことを隠さない
  assert.equal(agentIdOf({ agentId: 42 }), null);
  assert.equal(agentIdOf(null), null);
});

test('taskNotificationOf は完了通知から鍵と結果を取り出す', () => {
  const note = prompt([
    '<task-notification>',
    '<task-id>aae06781144f65807</task-id>',
    '<tool-use-id>toolu_01ABC</tool-use-id>',
    '<output-file>C:\\out\\report.md</output-file>',
    '<status>completed</status>',
    '<summary>Agent "探偵A: 調査" finished</summary>',
    '<result>本文</result>',
  ].join('\n'));
  // task-id は agentId と同じ値。ここでサブエージェントの記録とつながる
  assert.deepEqual(taskNotificationOf(note), {
    taskId: 'aae06781144f65807',
    toolUseId: 'toolu_01ABC',
    status: 'completed',
  });
});

test('taskNotificationOf は報告本文の中の同名タグを拾わない', () => {
  const note = prompt([
    '<task-notification>',
    '<task-id>outer</task-id>',
    '<status>failed</status>',
    '<result>',
    '<task-id>inner</task-id>',
    '<status>completed</status>',
    '</result>',
  ].join('\n'));
  // 報告本文にタグが入っていることが実際にある。<result> より手前だけを見る
  const got = taskNotificationOf(note);
  assert.equal(got.taskId, 'outer');
  assert.equal(got.status, 'failed');
});

test('taskNotificationOf は task-id が無い形と別種の行を外す', () => {
  // 実測91件のうち7件は task-id を持たない。つながる鍵が無いので採らない
  assert.equal(taskNotificationOf(prompt('<task-notification>\n<status>killed</status>')), null);
  assert.equal(taskNotificationOf(prompt('ふつうの指示')), null);
  assert.equal(taskNotificationOf(say('<task-notification>\n<task-id>x</task-id>')), null);
});

test('却下の種類と待ち専用ツールの一覧', () => {
  // user-rejected だけが「本人が断った」を意味する。ここを取り違えると表示の意味が変わる
  assert.equal(DENIAL_KINDS['user-rejected'], 'あなたが却下');
  assert.ok(ASK_TOOLS.has('AskUserQuestion'));
  assert.ok(ASK_TOOLS.has('ExitPlanMode'));
  assert.equal(ASK_TOOLS.has('Bash'), false);
});

test('ツール呼び出しの行は指示ではない', () => {
  assert.equal(isUserPrompt(call('Bash', { command: 'ls' })), false);
});
